# Generated by Django 3.1.2 on 2021-02-04 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='avalibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_order_quantity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
