# Generated by Django 3.1.2 on 2021-02-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210204_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
