# Generated by Django 3.1.2 on 2021-02-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210204_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis soluta in placeat et expedita atque ratione dolorem temporibus accusantium, excepturi dicta neque perferendis eaque natus quam quod vel, optio mollitia', max_length=350),
        ),
    ]
