# Generated by Django 3.1.2 on 2021-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210204_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Standard Speed Cube', 'Standard Speed Cube'), ('Pyramix', 'Pyramix'), ('Megamix', 'Megamix'), ('Skewb', 'Skewb'), ('Square-1', 'Square-1'), ('Mirror Cube', 'Mirror Cube'), ('Gear Cube', 'Gear Cube'), ('Locking Puzzels', 'Locking Puzzels')], max_length=50),
        ),
    ]
