# Generated by Django 3.1.2 on 2021-02-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210204_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='popularity',
        ),
    ]
