# Generated by Django 3.1.2 on 2022-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210207_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('BEDS', 'BEDS'), ('SOFA', 'SOFA'), ('TABLE', 'TABLE'), ('DINNING TABLE', 'DINNING TABLE'), ('CUBOARDS', 'CUBOARDS'), ('SHOW PICES', 'SHOW PICES'), ('DRESSING TABLE', 'DRESSING TABLE'), ('CENTER TABLE', 'CENTER TABLE')], max_length=50),
        ),
    ]
