# Generated by Django 3.1.2 on 2021-01-01 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210101_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
