# Generated by Django 3.1.2 on 2021-01-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='productId',
        ),
    ]
