# Generated by Django 3.1.2 on 2021-02-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210101_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imgLink',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
